apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application-secret
  namespace: secrets-governance
  labels:
    application: secrets-governance
    owner: platform-engineering
    environment: example
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore

  target:
    name: application-secret
    creationPolicy: Owner

  data:
    - secretKey: application-secret
      remoteRef:
        key: application-secret
