apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: secrets-governance
  labels:
    application: secrets-governance
    owner: platform-engineering
    environment: example
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      tenantId: "<AZURE-TENANT-ID>"
      vaultUrl: "https://<KEY-VAULT-NAME>.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-keyvault-credentials
          key: ClientID
        clientSecret:
          name: azure-keyvault-credentials
          key: ClientSecret
