apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-secret
  namespace: dops12-secrets
  labels:
    application: secrets-governance
    owner: platform-engineering
    environment: platform
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore

  target:
    name: platform-secret
    creationPolicy: Owner

  data:
    - secretKey: application-secret
      remoteRef:
        key: lab-secret
